# Generated by Django 3.0.6 on 2020-06-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_blog', '0002_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='cover',
        ),
    ]
