# Generated by Django 3.0.6 on 2020-06-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_blog', '0003_auto_20200613_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='image',
        ),
    ]
