# Generated by Django 3.0.6 on 2020-06-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_blog', '0006_auto_20200614_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_default.jpg', upload_to='images'),
        ),
    ]
